server:
  port: 8090
spring:
  spring:
    application:
      name: "loans"
    profiles:
      active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # or create-drop for dev
    show-sql: true
    sql:
      init:
        mode: always
#  jpa:
#    show-sql: true
#    sql:
#      init:
#        mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    hostname: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"