build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related prod APIs "
  contactDetails:
    name: "olti Berisha - Product Owner"
    email: "oltiberisha61@gmail.com"
  onCallSupport:
    - (944) 816-235
