services:
    rabbit:
      image: rabbitmq:4.0-management
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 5s
      extends:
        file: common-config.yml
        service: network-deploy-service

    configserver:
      image: "oltiberisha/configserver"
      container_name: configserver-ms
      ports:
        - "8071:8071"
      depends_on:
        rabbit:
          condition: service_healthy
      healthcheck:
        test: "curl --fail -silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - backend

    accounts:
        image: "oltiberisha/accounts"
        container_name: accounts-ms
        ports:
          - "8080:8080"
        depends_on:
          configserver:
            condition: service_healthy
        deploy:
          resources:
            limits:
              memory: 700m
        networks:
          - backend
        environment:
          SPRING_APPLIACTION_NAME: "accounts"
          SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
          SPRING_PROFILES_ACTIVE: default

    loans:
      image: "oltiberisha/loans"
      container_name: loans-ms
      ports:
      - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - backend
      environment:
        SPRING_APPLIACTION_NAME: "loans"
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        SPRING_PROFILES_ACTIVE: default

    cards:
      image: "oltiberisha/cards"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - backend
      environment:
        SPRING_APPLIACTION_NAME: "cards"
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        SPRING_PROFILES_ACTIVE: default

networks:
  backend:
    driver: "bridge"
