services:
#    rabbit:
#      image: rabbitmq:4.0-management
#      hostname: rabbitmq
#      ports:
#        - "5672:5672"
#        - "15672:15672"
#      healthcheck:
#        test: rabbitmq-diagnostics check_port_connectivity
#        interval: 10s
#        timeout: 5s
#        retries: 10
#        start_period: 15s
#      extends:
#        file: common-config.yml
#        service: network-deploy-service

    accountsdb:
      container_name: accountsdb
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: accountsdb
      extends:
        file: common-config.yml
        service: microservice-db-config

    loansdb:
      container_name: loansdb
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: loansdb
      extends:
        file: common-config.yml
        service: microservice-db-config

    cardsdb:
      container_name: cardsdb
      ports:
        - 3308:3306
      environment:
        MYSQL_DATABASE: cardsdb
      extends:
        file: common-config.yml
        service: microservice-db-config

    configserver:
      image: "oltiberisha/configserver"
      container_name: configserver-ms
      ports:
        - "8071:8071"
      healthcheck:
        test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      extends:
        file: common-config.yml
        service: microservice-base-config

    accounts:
      image: "oltiberisha/accounts"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      environment:
        SPRING_APPLICATION_NAME: "accounts"
        SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      depends_on:
        accountsdb:
          condition: service_healthy
        configserver:
          condition: service_healthy
      extends:
        file: common-config.yml
        service: microservice-configserver-config

    loans:
      image: "oltiberisha/loans"
      container_name: loans-ms
      ports:
        - "8090:8090"
      environment:
        SPRING_APPLICATION_NAME: "loans"
        SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      depends_on:
        loansdb:
          condition: service_healthy
        configserver:
          condition: service_healthy
      extends:
        file: common-config.yml
        service: microservice-configserver-config

    cards:
      image: "oltiberisha/cards"
      container_name: cards-ms
      ports:
        - "9000:9000"
      environment:
        SPRING_APPLICATION_NAME: "cards"
        SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      depends_on:
        cardsdb:
          condition: service_healthy
        configserver:
          condition: service_healthy
      extends:
        file: common-config.yml
        service: microservice-configserver-config

networks:
  backend:
    driver: "bridge"

#    configserver:
#      image: "oltiberisha/configserver"
#      container_name: configserver-ms
#      ports:
#        - "8071:8071"
#      depends_on:
#        rabbit:
#          condition: service_healthy
#      healthcheck:
#        test: "curl --fail -silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#        interval: 15s
#        timeout: 5s
#        retries: 10
#        start_period: 40s
#      extends:
#        file: common-config.yml
#        service: microservice-base-config
#
#    accounts:
#        image: "oltiberisha/accounts"
#        container_name: accounts-ms
#        ports:
#          - "8080:8080"
#        depends_on:
#          configserver:
#            condition: service_healthy
#        environment:
#          SPRING_APPLICATION_NAME: "accounts"
#        extends:
#          file: common-config.yml
#          service: microservice-configserver-config
#
#    loans:
#      image: "oltiberisha/loans"
#      container_name: loans-ms
#      ports:
#      - "8090:8090"
#      depends_on:
#        configserver:
#          condition: service_healthy
#      environment:
#        SPRING_APPLICATION_NAME: "loans"
#      extends:
#        file: common-config.yml
#        service: microservice-configserver-config
#
#    cards:
#      image: "oltiberisha/cards"
#      container_name: cards-ms
#      ports:
#        - "9000:9000"
#      depends_on:
#        configserver:
#          condition: service_healthy
#      environment:
#        SPRING_APPLICATION_NAME: "cards"
#      extends:
#        file: common-config.yml
#        service: microservice-configserver-config


